name: publish in npm
on:
  push:
    branches:
      - main
jobs: 
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: 
          node-version: 16
      - uses: actions/upload-artifact@v3
        with:
          name: react-absoluted
          path: .
  clear:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: react-absolute
          path: .
      - run: sudo rm -r docs
      - uses: actions/download-artifact@v3
        with:
          name: react-absolute
          path: .
  publish:
    needs: clear
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/download-artifact@v3
        with:
          name: react-abolute
          path: .
      - name: increment version
        run: sudo npm version patch --no-git-tag-verion
      - name: publish package
        run: sudo npm publish
